- name: pacman | install basic toolset
  become: True
  pacman:
    pkg:
    - htop
    - lm_sensors
    - lshw
    - nmap
    - python
    - python2
    - unzip
    - zip
    state: installed
  tags:
  - toolset
  - packages

- name: pacman | install workstation toolset
  become: True
  pacman:
    pkg:
    - xclip
    state: installed
  when: "usage is defined and 'working' in usage"
  tags:
  - toolset
  - packages
