- name: pacman | install basic toolset
  become: True
  pacman:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - htop
  - lm_sensors
  - lshw
  - nmap
  - python
  - python2
  - rofi
  - unzip
  - zip
  tags:
  - toolset
  - packages

- name: pacman | install workstation toolset
  become: True
  pacman:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - xclip
  when: "usage is defined and 'working' in usage"
  tags:
  - toolset
  - packages
