- name: homebrew | install basic toolset
  homebrew:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - htop
  - nmap
  - python
  - python@2
  - pinentry-mac
  tags:
  - toolset
  - packages
