- name: nix | install basic toolset
  nix:
    name:
    - htop
    - lm_sensors
    - lshw
    - nmap
    - python
    - python2
    - unzip
    - zip
    state: present
  tags:
  - toolset
  - packages

- name: nix | install workstation toolset
  nix:
    name:
    - xclip
    state: present
  when: "usage is defined and 'working' in usage"
  tags:
  - toolset
  - packages
