- name: file | ensure go directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
  - "{{ golang_gopath }}"
  tags:
  - golang
  - config

- name: template | ensure golang env variables
  template:
    src: environment.j2
    dest: "{{ env_dir }}/profile.d/golang.sh"

