- name: file | ensure go directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
  - "{{ golang_gopath }}"
  - "{{ golang_gopath }}/src"
  tags:
  - golang
  - config

- name: copy | ensure golang env variables
  copy:
    dest: "{{ env_dir }}/profile.d/golang.sh"
    content: |
      #!/usr/local/env bash
      # {{ ansible_managed }}

      export PATH="$PATH:{{ golang_gopath }}/bin"
      export GOPATH="{{ golang_gopath }}"
