---

# Setup symlink to current host and prepare environment
- hosts: localhost
  pre_tasks:
  - name: link hostname variables
    file:
      src: "{{ playbook_dir }}/host_vars/{{ ansible_hostname }}"
      dest: "{{ playbook_dir }}/host_vars/localhost"
      state: link
  roles:
  - environment

- import_playbook: playbooks/general.yml

- import_playbook: playbooks/workstation.yml
  when: "usage is defined and 'working' in usage"
