- name: file | ensure environment directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ env_dir }}"
  - "{{ env_dir }}/bin"
  - "{{ env_dir }}/profile.d"
  tags:
  - environment
  - config

- name: template | ensure global env variables
  template:
    src: environment.j2
    dest: "{{ env_dir }}/profile.d/global.sh"
