- name: shell | install gopass
  shell: go get -u {{ item }}
  environment:
    GOPATH: "{{ golang_gopath }}"
  with_items:
  - github.com/gopasspw/gopass
  changed_when: false
  tags:
  - gopass

- name: file | create config dir
  file:
    path: "{{ gopass_config_dir }}"
    state: directory
  tags:
  - gopass

- name: template | configure gopass
  template:
    src: "{{ item }}.j2"
    dest: "{{ gopass_config_dir }}/{{ item }}"
  with_items:
  - gopass_wrapper.sh
  tags:
  - gopass

- name: template | create gopass autocompletion
  template:
    src: completion.j2
    dest: "{{ env_dir }}/completion.d/_gopass"
  tags:
  - gopass

- name: template | create ssh-add-all script
  template:
    src: ssh-add-all.j2
    dest: "{{ env_dir }}/bin/ssh-add-all"
  tags:
  - gopass
