- name: pacman | install zsh and plugins
  become: True
  pacman:
    pkg:
    - python-virtualenvwrapper
    - zsh
    - zsh-completions
    state: installed
  tags:
  - zsh
  - packages

- include_tasks: configuration.yml
