- name: pacman | install zsh and plugins
  become: True
  pacman:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - python-virtualenvwrapper
  - zsh
  - zsh-completions
  tags:
  - zsh
  - packages

- include_tasks: configuration.yml
