- name: homebrew | install zsh and plugins
  homebrew:
    path: ${HOME}/.brew/bin
    pkg:
    - zsh
    - zsh-completions
    state: installed
  tags:
  - zsh
  - packages

- name: pip | install python plugins
  pip:
    name:
    - virtualenvwrapper
    state: present

- include_tasks: configuration.yml
