- name: homebrew | install zsh and plugins
  homebrew:
    pkg: "{{ item }}"
    state: installed
  with_items:
  - zsh
  - zsh-completions
  tags:
  - zsh
  - packages

- name: pip | install python plugins
  pip:
    pkg: "{{ item }}"
    state: present
  with_items:
  - virtualenvwrapper

- include_tasks: configuration.yml
