- name: file | ensure wallpaper directory
  file:
    name: "{{ env_dir }}/wallpapers"
    state: directory
  tags:
  - i3
  - configuration

- name: template | configure i3
  template:
    src: config.j2
    dest: "{{ ansible_user_dir }}/.config/i3/config"
  tags:
  - i3
  - configuration
