- name: homebrew | install vim
  homebrew:
    path: "{{ ansible_user_dir }}/.brew/bin"
    pkg:
    - "{{ vim_package }}"
    state: installed
  tags:
  - vim
  - packages

- include_tasks: configuration.yml
