---

- hosts: localhost
  pre_tasks:
  - name: link hostname variables
    file:
      src: "{{ playbook_dir }}/host_vars/{{ ansible_hostname }}"
      dest: "{{ playbook_dir }}/host_vars/localhost"
      state: link
  roles:
  - vim
